const GRID=20,CELL=18;
let snake,dir,food,score,interval,gameRunning=false;
function initSnake(){const el=document.getElementById('snake-board');el.innerHTML='';el.style.display='inline-grid';el.style.gridTemplateColumns=`repeat(${GRID},${CELL}px)`;el.style.gridTemplateRows=`repeat(${GRID},${CELL}px)`;el.style.gap='1px';el.style.background='#222';el.style.border='2px solid #444';el.style.borderRadius='4px';for(let i=0;i<GRID*GRID;i++){const c=document.createElement('div');c.className='cell';c.style.width=CELL+'px';c.style.height=CELL+'px';c.style.background='#111';el.appendChild(c);}}
function drawSnake(){const cells=document.querySelectorAll('#snake-board .cell');cells.forEach(c=>c.style.background='#111');snake.forEach((s,i)=>{cells[s.y*GRID+s.x].style.background=i===0?'#00f0f0':'#00b8b8';});cells[food.y*GRID+food.x].style.background='#f00060';}
function spawnFood(){do{food={x:Math.floor(Math.random()*GRID),y:Math.floor(Math.random()*GRID)};}while(snake.some(s=>s.x===food.x&&s.y===food.y));}
function tickSnake(){const head={x:snake[0].x+dir.x,y:snake[0].y+dir.y};if(head.x<0||head.x>=GRID||head.y<0||head.y>=GRID||snake.some(s=>s.x===head.x&&s.y===head.y)){clearInterval(interval);gameRunning=false;document.getElementById('snakeStartBtn').textContent='Play Again';return;}snake.unshift(head);if(head.x===food.x&&head.y===food.y){score+=10;document.getElementById('snake-score').textContent=score;spawnFood();}else snake.pop();drawSnake();}
function startSnake(){snake=[{x:10,y:10}];dir={x:1,y:0};score=0;document.getElementById('snake-score').textContent='0';document.getElementById('snakeStartBtn').textContent='Restart';gameRunning=true;spawnFood();drawSnake();clearInterval(interval);interval=setInterval(tickSnake,150);}
function snakeMove(d){if(!gameRunning)return;if(d==='up'&&dir.y!==1)dir={x:0,y:-1};else if(d==='down'&&dir.y!==-1)dir={x:0,y:1};else if(d==='left'&&dir.x!==1)dir={x:-1,y:0};else if(d==='right'&&dir.x!==-1)dir={x:1,y:0};}
document.addEventListener('keydown',e=>{if(!gameRunning)return;if(e.key==='ArrowUp')snakeMove('up');else if(e.key==='ArrowDown')snakeMove('down');else if(e.key==='ArrowLeft')snakeMove('left');else if(e.key==='ArrowRight')snakeMove('right');else return;e.preventDefault();});
